AlarmManager: Handle IO app exact alarm denials
Fix issue:
FATAL EXCEPTION: mqt_native_modules
Process: it.pagopa.io.app, PID: 7219
java.lang.SecurityException: Caller it.pagopa.io.app needs to hold android.permission.SCHEDULE_EXACT_ALARM to set exact alarms.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:376)
	at android.app.AlarmManager.setImpl(AlarmManager.java:954)
	at android.app.AlarmManager.setImpl(AlarmManager.java:907)
	at android.app.AlarmManager.setExact(AlarmManager.java:705)
	at com.dieam.reactnativepushnotification.modules.RNPushNotificationHelper.sendNotificationScheduledCore(RNPushNotificationHelper.java:181)
	at com.dieam.reactnativepushnotification.modules.RNPushNotificationHelper.sendNotificationScheduled(RNPushNotificationHelper.java:160)
	at com.dieam.reactnativepushnotification.modules.RNPushNotification.scheduleLocalNotification(RNPushNotification.java:183)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
	at java.lang.Thread.run(Thread.java:920)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.alarm.AlarmManagerService$5.set(AlarmManagerService.java:2615)
	at android.app.IAlarmManager$Stub.onTransact(IAlarmManager.java:203)
	at android.os.Binder.execTransactInternal(Binder.java:1179)
	at android.os.Binder.execTransact(Binder.java:1143)